### ISSUE TITLE
Wrong Package Type

### ISSUE THREAD

**Issue by XedinUnknown** [GrottoPress/jentil#1]
Hi,

Big advocate of doing things right. Saw that your theme complies with the coding standards and autoloading PSRs; the code is also better then all other themes that I've seen, and so I wanted to try it out.

Used Bedrock as part of my [Scotch on Rocks][] project. To my surprize, the [package type][composer\schema-type] is default, instead of `wordpress-theme`. This means that I cannot use the [`composer/installers`][composer\plugin-installers] to install the theme into the correct directory. As a result, WordPress doesn't see the theme, and anyone using Bedrock - IMHO currently the best way to WordPress - cannot use your theme.

[Scotch on Rocks]: https://github.com/Dhii/scotch-on-rocks
[composer\schema-type]: https://getcomposer.org/doc/04-schema.md#type
[composer\plugin-installers]: https://github.com/composer/installers

**Comment by akadusei** [comment]
@XedinUnknown Good to know I'm doing some things right :-)

See my answer in #6 

The package type of the `jentil-child` theme would be `wordpress-theme`.

**Comment by XedinUnknown** [comment]
Hi! For everything to work correctly, i.e. for WP to recognize the main theme as the parent theme, you would need to give it the correct package type just as well.

**Comment by XedinUnknown** [comment]
Also important because this theme can also be used as a starter. Same thing.

**Comment by akadusei** [comment]
If I get you right, you're looking at Jentil itself being used as a starter theme?

I'm looking at Jentil being used as **dependency** in a starter theme. The starter theme is supposed to call `Jentil()->run()`, before running it's own setups.

So the starter theme can override Jentil's features like it would a parent theme (eg `remove_action('wp_enqueue_scripts', [Jentil()->setup['styles'], 'enqueuePosts');`), even though Jentil would be installed as a `library`.

Let me see if I can quickly put together an example `jentil-child` theme (one that can also be used as a child theme by running the commands in the README.md). Will post you the link after I'm done. You can check and give me feedback.

It may also give me the opportunity to experience your problem myself.

Thanks.

**Comment by XedinUnknown** [comment]
Thanks.
However, if you want this theme to be usable as a parent theme, you'd need to declare the right package type anyhow.

**Comment by akadusei** [comment]
Finally managed to complete the starter for Jentil, and updated the docs to reflect this. Should give an idea of how Jentil is supposed to be consumed. Kindly take a look.

**Comment by XedinUnknown** [comment]
Hi! Sorry for no reply. I don't think I'll be able to test this any time soon.
