### ISSUE TITLE
Dependency Assets Give 404

### ISSUE THREAD

**Issue by XedinUnknown** [GrottoPress/jentil#5]
Like I mentioned before in #1, I use Bedrock, although if I wasn't, and was using this package as a Composer dependency in another way, the issue would still be the same.

Requests for many of the resources give 404 errors. Specifically, these are the requests for resources that come from packages other than this one - dependencies of this theme, such as `grottopress/wordpress-posts`. That's because, like I wrote in #3, the dependencies are no longer in the project's folder, but are children of the *root* project, and so there's no `vendor` folder in the theme. Right now it's the request for `vendor/grottopress/wordpress-posts/dist/styles/posts.min.css` that fails, but I imagine that the same will happen to any request that is made for a URL computed [like this][jentil\enqueue-posts], e.g. using [`FileSystem#themeDir()`][].

The only real solution that I know for this kind of problem is by using [Puli][]. With this, you can have providers, such as the `wordpress-posts` package, register resources, such as the `posts.min.css` file, in the repository. Then consumers, such as `jentil`, can enqueue that resource using a uniform URI, like `wordpress-posts/css/posts.css`. Puli will resolve that URI to an actual file's URL, wherever that file is.

I might have tried to fix this in a child theme, but unfortunately your code doesn't use a DI container, so I can't just override things, especially since the constructor of `Jentil` does not use IoC. In addition, the `Jentil` class is `final` and contains `private` members, which further complicates matters. The only way would be to actually change the way that things are done - in this package and the dependencies like `wordpress-posts`.

[jentil\enqueue-posts]: https://github.com/GrottoPress/jentil/blob/master/app/libraries/Setup/Styles.php#L114
[`FileSystem#themeDir()`]: https://github.com/GrottoPress/jentil/blob/master/app/libraries/Utilities/FileSystem.php#L190
[Puli]: http://puli.io/

**Comment by akadusei** [comment]
@XedinUnknown Acknowledged. I'll take a look at Puli.

**Comment by XedinUnknown** [comment]
Thanks. I also encourage you to consider these improvements:

- Have more IoC, i.e. make a more generic theme class that can *accept* a list of "setups".
- Do not declare the class as `final`. It should be open for extension. There is no real reason to disallow that. In fact, I've never seen a legitimate use of `final` for classes.
- Declare internal methods as `protected` instead of `private`. Same as `final`, using the `protected` access modifier makes extension very difficult, and prevents code re-use.
