### ISSUE TITLE
Cannot run `composer run child`

### ISSUE THREAD

**Issue by XedinUnknown** [GrottoPress/jentil#6]
The docs mention that I can run `composer run child` to use a child theme. However, this gives the following error:
> Script "child" is not defined in this package

Which is true: nothing of this sort exists in `composer.json`.

**Comment by akadusei** [comment]
@XedinUnknown That's true. Sorry about that. It's something I mean to include later, hopefully before the next release. Currently, I'm thinking to write a `jentil-child` theme (full of example codes), from which jentil is *required* as a dependency. The docs were supposed to be in that child, not this one.

I'll correct it soon.
